version: "3.7"

services:
  mongo:
    container_name: exhibition_mongo
    image: mongo:4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"

  server:
    container_name: exhibition_server
    image: <%=serverTag%>
    depends_on:
      - "mongo"
    environment:
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      HOSTNAME: "${HOSTNAME}"

  gateway:
    container_name: exhibition_gateway
    image: <%=gatewayTag%>
    ports:
      - 80:80
    depends_on:
      - server
