version: '3.7'

services:
  mongo:
    container_name: exhibition_mongo
    image: mongo:4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 27017:27017

  gateway:
    container_name: exhibition_gateway
    image: nginx
    ports:
      - 80:80
    volumes:
      - ../gateway/development/conf.d:/etc/nginx/conf.d
      - ../gateway/development/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - ui

  server:
    container_name: exhibition_server
    build: ../server
    volumes:
      - ../server:/usr/app
      - ../repositories:/var/lib/chomim/repositories
    depends_on:
      - 'mongo'
    environment:
      DATABASE_PASSWORD: "${DB_PASSWORD}"
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
    ports:
      - 8080:8080

  ui:
    container_name: exhibition_ui
    build: ../ui
    stdin_open: true
    volumes:
      - ../ui:/usr/app
    ports:
      - 3000:3000
